230419 수요일 군AI 실습 자료입니다.   
본 내용은 IIPL (Intelligent Information Processing Lab) 소속 석사과정 유승욱 조교가 작성하였습니다.   
참고 자료: MIT Introduction to Deep Learning 6.S191: Lecture 1

> Lecture 1   
- Tensors in TensorFlow
- Computations on Tensors
- Custom Dense Layer
- TensorFlow Dense Layer
- Loss
- Gradient Descent
- Regularization
- Advanced Example: MNIST


### Libraries

In [ ]:
import tensorflow as tf
import tensorflow_datasets as tfds

### Tensors in TensorFlow
The **shape** of a Tensor defines its number of dimensions and the size of each dimension.   
The **rank** of a Tensor provides the number of dimensions (n-dimensions) -- you can also think of this as the Tensor's order or degree.

In [ ]:
# 0-d Tensors like scalar
sport  = tf.constant('Tennis', tf.string)
number = tf.constant(3.141592, tf.float64)

print("`sport` is a {}-d tensor".format(tf.rank(sport).numpy()))
print("`number` is a {}-d tensor".format(tf.rank(number).numpy()))

`sport` is a 0-d tensor
`number` is a 0-d tensor


In [ ]:
# 1-d Tensors like lists and vectors
sports  = tf.constant(['Tennis', 'Basketball'], tf.string)
numbers = tf.constant([3.141592, 1.414213, 2.71821], tf.float64)

print("`sports` is a {}-d Tensor with shape: {}".format(tf.rank(sports).numpy(), tf.shape(sports)))
print("`numbers` is a {}-d Tensor with shape: {}".format(tf.rank(numbers).numpy(), tf.shape(numbers)))

`sports` is a 1-d Tensor with shape: [2]
`numbers` is a 1-d Tensor with shape: [3]


In [ ]:
# 2-d Tensors like single sentence (word count * word dimension)
# 3-d Tensors like batch sentences (batch_size * word count * word dimension)

# 3-d Tensors like single image (height * shape * color channels) 
# 4-d Tensors like batch images (batch size * height * shape * color channels)

In [ ]:
""" TODO: Make a tensors using tf.zeros & tf.ones """

# You can make Tensors easily using tf.zeros & tf.ones
zeros = tf.zeros([1, 2])
ones  = tf.ones([2, 1])

print(zeros)
print(ones)

tf.Tensor([[0. 0.]], shape=(1, 2), dtype=float32)
tf.Tensor(
[[1.]
 [1.]], shape=(2, 1), dtype=float32)


In [ ]:
""" TODO: Define a 2-d Tensor """

matrix = tf.constant([[1.0, 2.0], [3.0, 4.0]], tf.float64)

print(matrix.shape)
print(tf.rank(matrix))

assert isinstance(matrix, tf.Tensor), "matrix must be a tf Tensor object"
assert tf.rank(matrix).numpy() == 2, "matrix must be of rank 2"

(2, 2)
tf.Tensor(2, shape=(), dtype=int32)


In [ ]:
""" TODO: Define a 4-d Tensor
    with size 10 * 256 * 256 * 3 using tf.zeros """

images = tf.zeros([10, 256, 256, 3])

print(images.shape)
print(tf.rank(images))

assert isinstance(images, tf.Tensor), "matrix must be a tf Tensor object"
assert tf.rank(images).numpy() == 4, "matrix must be of rank 4"
assert tf.shape(images).numpy().tolist() == [10, 256, 256, 3], "matrix is incorrect shape"

In [ ]:
# Check matrix's row & column
row_vector    = matrix[1]
column_vector = matrix[:,1]
scalar        = matrix[0, 1]

print("`row_vector`: {}".format(row_vector.numpy()))
print("`column_vector`: {}".format(column_vector.numpy()))
print("`scalar`: {}".format(scalar.numpy()))

`row_vector`: [3. 4.]
`column_vector`: [2. 4.]
`scalar`: 2.0


### Computations on Tensors

In [ ]:
# Compare add computations between scalars vs. Tensors
a = tf.constant(15)
b = tf.constant(61)

c1 = 15 + 61
print(c1)

c2 = tf.add(a, b)
print(c2)

76
tf.Tensor(76, shape=(), dtype=int32)


In [ ]:
""" TODO: Try some other computations """

# Other computations
d = tf.subtract(a, b)
print(d)

e = tf.multiply(a, b)
print(e)

f = tf.divide(a, b)
print(f)

tf.Tensor(-46, shape=(), dtype=int32)
tf.Tensor(915, shape=(), dtype=int32)
tf.Tensor(0.2459016393442623, shape=(), dtype=float64)


### Custom Dense layer

In [ ]:
""" TODO: Make your custom dense layer """ 

# Custom dense layer
class OurDenseLayer(tf.keras.layers.Layer):
  def __init__(self, n_output_nodes):
    super(OurDenseLayer, self).__init__()
    self.n_output_nodes = n_output_nodes

  def build(self, input_shape):
    # Initialize weights and bias
    d = int(input_shape[-1])
    self.W = self.add_weight('weight', shape=[d, self.n_output_nodes])
    self.b = self.add_weight('bias', shape=[1, self.n_output_nodes])

  def call(self, x):
    # Forward propagate the inputs
    z = tf.matmul(x, self.W) + self.b

    # Feed through a non-linear activation
    y = tf.math.sigmoid(z)
    return y

In [ ]:
custom_layer = OurDenseLayer(3)
custom_layer.build((1, 2))

x_input = tf.constant([[1, 2.]], shape=(1, 2))
y       = custom_layer.call(x_input)

In [ ]:
print('input      : {}'.format(x_input))
print('input shape: {}\n'.format(x_input.shape))

print('output      : {}'.format(y.numpy()))
print('output shape: {}'.format(y.numpy().shape))

input      : [[1. 2.]]
input shape: (1, 2)

output      : [[0.69371545 0.6079396  0.12837772]]
output shape: (1, 3)


### TensorFlow Dense Layer

In [ ]:
# One dense layer
layer = tf.keras.layers.Dense(units=2)

# Multiple dense layers
model = tf.keras.Sequential([
    tf.keras.layers.Dense(10),
    tf.keras.layers.Dense(2)
])

In [ ]:
""" TODO: Concatenate dense layers """

# Deep Neural Network (DNN) using multiple dense layers
input_size = 10
layer1 = tf.keras.layers.Dense(units=64, activation='relu', input_shape=(input_size,))
layer2 = tf.keras.layers.Dense(units=32, activation='relu')
layer3 = tf.keras.layers.Dense(units=16, activation='relu')
layer4 = tf.keras.layers.Dense(units=1)

model = tf.keras.Sequential([layer1, layer2, layer3, layer4])
for layer in model.layers:
  print(layer)

In [ ]:
# TensorFlow dense layer
class TFDenseLayer(tf.keras.Model):
  def __init__(self, n_output_nodes):
    super(TFDenseLayer, self).__init__()
    self.dense_layer = tf.keras.layers.Dense(units=n_output_nodes, activation='sigmoid')

  def call(self, x):
    # Forward propagate the inputs
    # Feed through a non-linear activation
    return self.dense_layer(x)

In [ ]:
custom_layer = TFDenseLayer(3)

x_input = tf.constant([[1, 2.]], shape=(1, 2))
y       = custom_layer.call(x_input)

In [ ]:
print('input      : {}'.format(x_input))
print('input shape: {}\n'.format(x_input.shape))

print('output      : {}'.format(y.numpy()))
print('output shape: {}'.format(y.numpy().shape))

input      : [[1. 2.]]
input shape: (1, 2)

output      : [[0.12574184 0.7328146  0.8921796 ]]
output shape: (1, 3)


### Loss

In [ ]:
# Binary cross entropy loss (BCE)
# Output is a probability between 0 and 1
y         = [1, 0, 1]
predicted = [0.1, 0.8, 0.6]

loss = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(y, predicted))

print(loss)

tf.Tensor(2.5790925, shape=(), dtype=float32)


In [ ]:
""" TODO: Construct MSE Loss """

# Mean square error loss (MSE)
# Output is a continuous real number
y         = [90, 20, 95]
predicted = [30, 80, 85]

loss1 = tf.reduce_mean(tf.square(tf.subtract(y, predicted)))
loss2 = tf.keras.losses.MSE(y, predicted)

print(loss1)
print(loss2)

tf.Tensor(2433, shape=(), dtype=int32)
tf.Tensor(2433, shape=(), dtype=int32)


### Gradient Descent

In [ ]:
# Initialize weights randomly using normal distribution
weights = tf.Variable([tf.random.normal([2, 2])])

print(weights)

<tf.Variable 'Variable:0' shape=(1, 2, 2) dtype=float32, numpy=
array([[[ 1.1022378, -1.0195255],
        [ 0.5444023,  1.2773194]]], dtype=float32)>


In [ ]:
""" TODO: Use tf.GradientTape() and define y """

# tf.GradientTape() records relevant operatinos onto a 'tape'
x = tf.Variable(3.0)
with tf.GradientTape() as tape:
  y = x * x
dy_dx = tape.gradient(y, x)

print(dy_dx.numpy())

6.0


In [ ]:
# Gradient descent for Test
while True:
  with tf.GradientTape() as tape:
    def compute_loss(weights): return weights
    loss = compute_loss(weights)
    gradient = tape.gradient(loss, weights)

  lr = 0.0001
  weights = weights - lr * gradient
  break

In [ ]:
# Various gradient descent algorithms
# learn more: https://www.ruder.io/optimizing-gradient-descent/
sgd      = tf.keras.optimizers.SGD
adam     = tf.keras.optimizers.Adam
adadelta = tf.keras.optimizers.Adadelta
adagrad  = tf.keras.optimizers.Adagrad

print(sgd)
print(adam)
print(adadelta)
print(adagrad)
try: rmsprop  = tf.keras.optimizers.RMSProp
except: print('failed to define RMSProp')

<class 'keras.optimizers.sgd.SGD'>
<class 'keras.optimizers.adam.Adam'>
<class 'keras.optimizers.adadelta.Adadelta'>
<class 'keras.optimizers.adagrad.Adagrad'>
failed to define RMSProp


### Regularization

In [ ]:
# Dropout
tf.keras.layers.Dropout(rate=0.5)

In [ ]:
# Early stopping
tf.keras.callbacks.EarlyStopping(monitor='val_loss')

### Advanced Example: MNIST

In [ ]:
# Download MNIST datasets
(ds_train, ds_test), ds_info = tfds.load(
    'mnist',
    split=['train', 'test'],
    shuffle_files=True,
    as_supervised=True,
    with_info=True,
)

Dl Completed...:   0%|          | 0/5 [00:00<?, ? file/s]

Dataset mnist downloaded and prepared to /root/tensorflow_datasets/mnist/3.0.1. Subsequent calls will reuse this data.


In [ ]:
# Preprocess train data
def normalize_img(image, label):
  """ Normalizes images: `uint8` -> `float32`. """
  return tf.cast(image, tf.float32) / 255., label

ds_train = ds_train.map(
    normalize_img, num_parallel_calls=tf.data.AUTOTUNE)
ds_train = ds_train.cache()
ds_train = ds_train.shuffle(ds_info.splits['train'].num_examples)
ds_train = ds_train.batch(128)
ds_train = ds_train.prefetch(tf.data.AUTOTUNE)

In [ ]:
# Preprocess test data
ds_test = ds_test.map(
    normalize_img, num_parallel_calls=tf.data.AUTOTUNE)
ds_test = ds_test.batch(128)
ds_test = ds_test.cache()
ds_test = ds_test.prefetch(tf.data.AUTOTUNE)

In [ ]:
# Train model
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dense(10)
])

model.compile(
    optimizer=tf.keras.optimizers.Adam(0.001),
    loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
    metrics=[tf.keras.metrics.SparseCategoricalAccuracy()],
)

model.fit(
    ds_train,
    epochs=6,
    validation_data=ds_test,
)

Epoch 1/6
469/469 [==============================] - 20s 18ms/step - loss: 0.3591 - sparse_categorical_accuracy: 0.8998 - val_loss: 0.1991 - val_sparse_categorical_accuracy: 0.9443
Epoch 2/6
469/469 [==============================] - 7s 14ms/step - loss: 0.1690 - sparse_categorical_accuracy: 0.9516 - val_loss: 0.1403 - val_sparse_categorical_accuracy: 0.9576
Epoch 3/6
469/469 [==============================] - 3s 6ms/step - loss: 0.1204 - sparse_categorical_accuracy: 0.9657 - val_loss: 0.1105 - val_sparse_categorical_accuracy: 0.9676
Epoch 4/6
469/469 [==============================] - 4s 8ms/step - loss: 0.0937 - sparse_categorical_accuracy: 0.9728 - val_loss: 0.1040 - val_sparse_categorical_accuracy: 0.9693
Epoch 5/6
469/469 [==============================] - 3s 6ms/step - loss: 0.0759 - sparse_categorical_accuracy: 0.9783 - val_loss: 0.0868 - val_sparse_categorical_accuracy: 0.9742
Epoch 6/6
469/469 [==============================] - 3s 6ms/step - loss: 0.0621 - sparse_categorical_a